### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by capriciousduck** [actionsflow/actionsflow#21]
How to deploy this app on Heroku?

**Comment by theowenyoung** [comment]
Hi,  @capriciousduck , Unfortunately the answer to your question is: not yet.

For securiy reasons Heroku does not provide to the users the ability to run priviledged containers because the container could access to host capabilities. But actionsflow need root permission to run docker actions.

Heroku limit: https://devcenter.heroku.com/articles/container-registry-and-runtime#testing-an-image-locally
